android.useAndroidX=true
android.enableJetifier=true
android.nonFinalResIds=false
android.nonTransitiveRClass=false
android.builtInKotlin=false
android.newDsl=false
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=256m -Dfile.encoding=UTF-8
kotlin.compiler.execution.strategy=out-of-process
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.caching=true
org.gradle.parallel=false
systemProp.file.encoding=utf-8
